import { Eye } from "lucide-react";
import { useState } from "react";
import { useScrollTrigger } from "../hooks/useScrollTrigger";
import ProjectModal, { type Project } from "./ProjectModal";

const projects: Project[] = [
  {
    id: 1,
    title: "Project Helios",
    category: "Solar Propulsion",
    description: "Solar sail spacecraft for deep space exploration",
    longDescription:
      "Project Helios is our flagship solar sail mission, deploying a 1,200 m² reflective sail to harness photon pressure for propellant-free deep space travel. The spacecraft achieved a record-breaking 0.05c velocity during its maiden voyage to the asteroid belt, demonstrating the viability of solar sailing for interplanetary cargo missions.",
    tags: [
      {
        name: "Solar Sail",
        description:
          "A propulsion technology that uses large reflective sheets to harness radiation pressure from sunlight — no fuel required, enabling indefinite acceleration in space.",
      },
      {
        name: "Deep Space",
        description:
          "Refers to regions beyond low Earth orbit, typically beyond the Moon. Deep space missions require advanced life support, communication, and navigation over vast distances.",
      },
      {
        name: "Propellant-Free",
        description:
          "Travel without chemical rockets or onboard propellant. Solar sails and ion drives are examples — they generate thrust from photons or electrical energy rather than burning fuel.",
      },
      {
        name: "Asteroid Belt",
        description:
          "A region between Mars and Jupiter containing millions of rocky bodies. It is a prime target for resource mining and scientific study of early solar system formation.",
      },
    ],
    color: "#00f5ff",
    bgGradient:
      "linear-gradient(135deg, #050a1a 0%, #0d2040 50%, #001a2e 100%)",
    image: "/assets/generated/project-helios.dim_800x480.jpg",
  },
  {
    id: 2,
    title: "Nexus Station",
    category: "Space Habitat",
    description: "Modular orbital habitat for 50 crew members",
    longDescription:
      "Nexus Station is a revolutionary modular orbital habitat designed to house 50 crew members in comfort and safety at L2 Lagrange point. Featuring artificial gravity through centrifugal rotation, advanced hydroponics for food production, and a closed-loop life support system with 99.9% efficiency, it represents the future of long-duration human spaceflight.",
    tags: [
      {
        name: "Orbital Habitat",
        description:
          "A permanently crewed structure in space orbit designed for long-duration human living, working, and research — the foundation of sustained human presence beyond Earth.",
      },
      {
        name: "Artificial Gravity",
        description:
          "Generated by rotating the station so centrifugal force mimics the pull of gravity. This prevents the bone and muscle loss that astronauts experience in prolonged weightlessness.",
      },
      {
        name: "Life Support",
        description:
          "Closed-loop systems that recycle air, water, and waste to keep crew alive. The Nexus system achieves 99.9% efficiency, meaning almost nothing is wasted or vented.",
      },
      {
        name: "L2 Lagrange",
        description:
          "A gravitationally stable point in space about 1.5 million km from Earth, on the far side from the Sun. Ideal for space stations and telescopes as it requires minimal fuel to stay in position.",
      },
    ],
    color: "#c084fc",
    bgGradient:
      "linear-gradient(135deg, #0d0520 0%, #1a0535 50%, #0a0e2a 100%)",
    image: "/assets/generated/project-nexus.dim_800x480.jpg",
  },
  {
    id: 3,
    title: "Quantum Link",
    category: "Communications",
    description: "Interplanetary quantum communication network",
    longDescription:
      "Quantum Link establishes the first interplanetary quantum key distribution network, enabling theoretically unbreakable encrypted communications between Earth, the Moon, and Mars. The system uses entangled photon pairs transmitted via high-power laser arrays, achieving 100 Gbps data rates with zero latency compensation algorithms.",
    tags: [
      {
        name: "Quantum Encryption",
        description:
          "Uses quantum mechanics principles so any attempt to intercept a message physically alters it — making eavesdropping mathematically impossible and communications truly unbreakable.",
      },
      {
        name: "Laser Comms",
        description:
          "High-powered laser beams transmit data at speeds far beyond traditional radio waves, enabling 100 Gbps data rates across planetary distances in space.",
      },
      {
        name: "Mars Network",
        description:
          "An interplanetary communications infrastructure connecting Earth, Moon, and Mars relay nodes to enable real-time coordination for crewed Mars missions and colonies.",
      },
      {
        name: "Zero Latency",
        description:
          "Advanced compensation algorithms that predict and correct for the signal travel time (up to 20 minutes Earth-to-Mars), enabling near-real-time command and control of remote systems.",
      },
    ],
    color: "#34d399",
    bgGradient:
      "linear-gradient(135deg, #021a10 0%, #053520 50%, #0a1a15 100%)",
    image: "/assets/generated/project-quantumlink.dim_800x480.jpg",
  },
  {
    id: 4,
    title: "Titan Probe",
    category: "Exploration",
    description: "Autonomous submarine for Titan's methane seas",
    longDescription:
      "The Titan Probe is an autonomous submarine designed to explore the hydrocarbon seas of Saturn's moon Titan. Powered by a radioisotope thermoelectric generator, it can operate for 20 years in liquid methane at -179°C, collecting samples and transmitting high-resolution sonar maps of Titan's seafloor geology.",
    tags: [
      {
        name: "Titan",
        description:
          "Saturn's largest moon and the only moon in the solar system with a thick atmosphere and liquid surface lakes — made of liquid methane and ethane, not water.",
      },
      {
        name: "Submarine",
        description:
          "An autonomous underwater vehicle designed to navigate and sample the hydrocarbon seas of Titan, surviving pressures and temperatures of −179°C where no conventional material works.",
      },
      {
        name: "RTG Power",
        description:
          "Radioisotope Thermoelectric Generator — converts heat from decaying plutonium into electricity. Used on Voyager, Cassini, and Curiosity where solar panels cannot function due to distance from the Sun.",
      },
      {
        name: "Hydrocarbon Seas",
        description:
          "Titan's surface features large lakes and seas of liquid methane and ethane. These are the only stable surface liquids known to exist on any world besides Earth, making Titan unique in our solar system.",
      },
    ],
    color: "#fb923c",
    bgGradient:
      "linear-gradient(135deg, #1a0a00 0%, #2d1500 50%, #1a0800 100%)",
    image: "/assets/generated/project-titan.dim_800x480.jpg",
  },
  {
    id: 5,
    title: "Aurora Drive",
    category: "Propulsion",
    description: "Fusion-powered spacecraft engine prototype",
    longDescription:
      "Aurora Drive is our most ambitious propulsion project — a compact fusion reactor engine that achieves specific impulse values of 100,000 seconds. Using deuterium-helium-3 fuel, the engine produces 500 kN of thrust with near-zero radioactive waste, potentially reducing Earth-to-Mars transit time to just 39 days.",
    tags: [
      {
        name: "Fusion Drive",
        description:
          "A propulsion system powered by nuclear fusion — the same process that powers the Sun. It produces enormous energy from tiny amounts of fuel, enabling very high thrust and efficiency simultaneously.",
      },
      {
        name: "He-3 Fuel",
        description:
          "Helium-3 is a rare isotope that, when fused with deuterium, produces very little radioactive waste. It is abundant on the Moon and in the outer solar system, making it ideal for clean space propulsion.",
      },
      {
        name: "High ISP",
        description:
          "Specific Impulse (ISP) measures propellant efficiency. Aurora Drive achieves 100,000 seconds ISP — compared to 450s for chemical rockets — meaning far more thrust per unit of fuel consumed.",
      },
      {
        name: "Mars Transit",
        description:
          "With fusion propulsion, the Earth-to-Mars journey shrinks from 7–9 months (chemical rockets) to just 39 days, making regular crewed Mars missions practical and safe.",
      },
    ],
    color: "#f472b6",
    bgGradient:
      "linear-gradient(135deg, #1a0515 0%, #2d0a25 50%, #150310 100%)",
    image: "/assets/generated/project-aurora.dim_800x480.jpg",
  },
  {
    id: 6,
    title: "Orbital Forge",
    category: "Manufacturing",
    description: "Zero-gravity manufacturing platform in LEO",
    longDescription:
      "Orbital Forge is a commercial manufacturing platform in low Earth orbit that leverages microgravity to produce materials impossible to create on Earth. From perfect spherical bearings to ultra-pure pharmaceutical crystals and exotic alloys, it represents the dawn of the space manufacturing economy, with 12 production modules currently operational.",
    tags: [
      {
        name: "Microgravity",
        description:
          "The near-weightless environment in Earth orbit where gravity effects are almost eliminated. This allows materials to form without the defects caused by gravity — enabling superior alloys, crystals, and pharmaceuticals impossible to make on Earth.",
      },
      {
        name: "Manufacturing",
        description:
          "Space-based production of high-value goods like perfect spherical bearings, ultra-pure pharmaceutical crystals, and exotic metal alloys that fetch premium prices for use in advanced technology on Earth.",
      },
      {
        name: "LEO Platform",
        description:
          "A facility in Low Earth Orbit (approximately 400 km altitude) — close enough for regular supply missions from Earth, yet far enough to maintain true microgravity manufacturing conditions continuously.",
      },
      {
        name: "Space Economy",
        description:
          "The growing commercial ecosystem of businesses that operate in space or depend on space infrastructure. Manufacturing, tourism, mining, and communications are expected to make it a multi-trillion dollar industry by 2040.",
      },
    ],
    color: "#60a5fa",
    bgGradient:
      "linear-gradient(135deg, #020a1a 0%, #051535 50%, #020d28 100%)",
    image: "/assets/generated/project-orbital.dim_800x480.jpg",
  },
];

export default function Portfolio() {
  const [selectedProject, setSelectedProject] = useState<Project | null>(null);
  const { ref: sectionRef, isVisible } = useScrollTrigger(0.05);

  return (
    <section
      id="portfolio"
      ref={sectionRef as React.RefObject<HTMLElement>}
      className="relative z-10 py-24 sm:py-32 px-4 sm:px-6"
    >
      <div className="max-w-7xl mx-auto">
        {/* Section header */}
        <div
          className={`text-center mb-16 scroll-reveal ${isVisible ? "visible" : ""}`}
        >
          <span className="text-space-cyan text-xs font-semibold tracking-widest uppercase font-exo mb-3 block">
            Our Work
          </span>
          <h2 className="section-title text-5xl sm:text-6xl text-white mb-4">
            Project <span className="text-space-cyan">Portfolio</span>
          </h2>
          <div className="w-24 h-1 mx-auto rounded-full section-glow-divider" />
          <p className="text-white/60 mt-6 max-w-2xl mx-auto font-exo text-base">
            Explore our groundbreaking projects that are redefining the
            boundaries of space exploration and aerospace engineering.
          </p>
        </div>

        {/* Grid */}
        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-8">
          {projects.map((project, i) => (
            <button
              key={project.id}
              type="button"
              className={`portfolio-card glass-card rounded-2xl overflow-hidden cursor-pointer scroll-reveal text-left w-full ${isVisible ? "visible" : ""}`}
              style={
                {
                  transitionDelay: `${i * 0.1}s`,
                  "--card-color": project.color,
                } as React.CSSProperties
              }
              onClick={() => setSelectedProject(project)}
            >
              {/* Visual area */}
              <div
                className="relative h-64 overflow-hidden"
                style={{ background: project.bgGradient }}
              >
                {/* Project image */}
                {project.image && (
                  <img
                    src={project.image}
                    alt={project.title}
                    className="absolute inset-0 w-full h-full object-cover opacity-80"
                  />
                )}
                {/* Overlay gradient for readability */}
                <div
                  className="absolute inset-0"
                  style={{
                    background:
                      "linear-gradient(to top, rgba(0,0,0,0.6) 0%, transparent 60%)",
                  }}
                />
                {/* Project number */}
                <div className="absolute inset-0 flex items-center justify-center">
                  <span className="font-orbitron font-black text-6xl opacity-10 text-white select-none">
                    {project.id.toString().padStart(2, "0")}
                  </span>
                </div>
                {/* Glow orb */}
                <div
                  className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-24 h-24 rounded-full blur-2xl opacity-20"
                  style={{ background: project.color }}
                />
                {/* Hover overlay */}
                <div className="overlay">
                  <div className="flex items-center gap-2 text-white/90 text-sm font-semibold font-exo">
                    <Eye className="w-4 h-4" />
                    View Project
                  </div>
                </div>
              </div>

              {/* Info */}
              <div className="p-6">
                <span
                  className="text-sm font-semibold tracking-widest uppercase px-2.5 py-1 rounded-full mb-3 inline-block"
                  style={{
                    background: `${project.color}15`,
                    color: project.color,
                    border: `1px solid ${project.color}30`,
                  }}
                >
                  {project.category}
                </span>
                <h3 className="font-orbitron font-bold text-xl text-white mb-2">
                  {project.title}
                </h3>
                <p className="text-white/55 text-base font-exo leading-relaxed">
                  {project.description}
                </p>
              </div>
            </button>
          ))}
        </div>
      </div>

      {/* Modal */}
      <ProjectModal
        project={selectedProject}
        onClose={() => setSelectedProject(null)}
      />
    </section>
  );
}
